# Generated by Django 5.2.15 on 2026-07-12 23:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('name', models.CharField(max_length=255, verbose_name='نام ساختمان')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی')),
                ('total_floors', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد طبقات')),
                ('construction_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال ساخت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'ساختمان',
                'verbose_name_plural': 'ساختمان\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('name', models.CharField(max_length=50, verbose_name='نام/شماره بلوک')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='buildings.building', verbose_name='ساختمان')),
            ],
            options={
                'verbose_name': 'بلوک',
                'verbose_name_plural': 'بلوک\u200cها',
                'unique_together': {('building', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('unit_number', models.CharField(max_length=20, verbose_name='شماره واحد')),
                ('floor', models.SmallIntegerField(verbose_name='طبقه')),
                ('area', models.DecimalField(decimal_places=2, help_text='برای فرمول شارژ (fixed + area × rate) استفاده می\u200cشه', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='متراژ (متر مربع)')),
                ('unit_type', models.CharField(choices=[('residential', 'مسکونی'), ('commercial', 'تجاری'), ('office', 'اداری')], default='residential', max_length=20, verbose_name='نوع واحد')),
                ('bedroom_count', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد خواب')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='buildings.block', verbose_name='بلوک')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='buildings.building', verbose_name='ساختمان')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'واحد',
                'verbose_name_plural': 'واحدها',
                'unique_together': {('building', 'unit_number')},
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('number', models.CharField(max_length=20, verbose_name='شماره انباری')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='buildings.building', verbose_name='ساختمان')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storages', to='buildings.unit', verbose_name='واحد متصل\u200cشده')),
            ],
            options={
                'verbose_name': 'انباری',
                'verbose_name_plural': 'انباری\u200cها',
                'unique_together': {('building', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف\u200cشده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('number', models.CharField(max_length=20, verbose_name='شماره پارکینگ')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkings', to='buildings.building', verbose_name='ساختمان')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('unit', models.ForeignKey(blank=True, help_text='اگه پارکینگ مشترک/بدون تخصیص باشه خالی بذار', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parkings', to='buildings.unit', verbose_name='واحد متصل\u200cشده')),
            ],
            options={
                'verbose_name': 'پارکینگ',
                'verbose_name_plural': 'پارکینگ\u200cها',
                'unique_together': {('building', 'number')},
            },
        ),
    ]
